# config.yml
# Configuration settings for the ConsignTracker application

mongodb:
  uri: "mongodb://localhost:27017"
  database: "consign_tracker_db"
  collection: "consign_tracker" 
  master_collection: "consign_tracker_master"

admin:
  username: "admin"
  password: "Admin123-1"

email:
  # The Gmail address you are sending from
  smtp_user: "cbacut@up.edu.ph" 
  smtp_password: "aqug nyui hcqa vdgv" 
